version: '3.8'

services:
    buleberry_ts:
      container_name: buleberry_ts
      tty: true
      init: true
      user: node
      build:
        context: .
        dockerfile: ./Dockerfile
      volumes:
        - ./:/app:cache
        - node_modules:/app/node_modules
      environment:
        NODE_ENV: development

volumes:
  node_modules: